FROM golang:1.20 AS builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go install github.com/go-delve/delve/cmd/dlv@latest
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -gcflags="all=-trimpath=`pwd` -N -l" \
     -asmflags "all=-trimpath=`pwd`" -o remotedlv .

FROM ubuntu:20.04

WORKDIR /app

COPY --from=builder /app/remotedlv /app/remotedlv
COPY --from=builder /go/bin/dlv /dlv

CMD ["sleep", "infinity"]
